## The Business Problem

### Anjum Hotel has been running various marketing campaigns to increase room bookings and enhance brand visibility. 
### Despite investing significantly in these campaigns, the hotel management is unsure which channels yield the highest return on investment (ROI) and which campaign strategies are most effective. They want to optimize their marketing spend and maximize bookings and revenue.

## Objective :
### To analyze the effectiveness of different marketing campaigns and channels, determine which ones drive the most bookings and revenue, and provide data-driven recommendations to optimize future marketing efforts.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_excel('Anjum Marketing Campaigns.xlsx')

In [4]:
df.head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue
0,1,Campaign 1,2024-02-02 04:16:35.177,2024-02-26 04:16:35.177,Radio,Seniors,24809,6540,2104.000000,18703,7048.40
1,2,Campaign 2,2023-08-18 04:16:35.178,2023-09-03 04:16:35.178,Billboards,Seniors,193273,1154,11565.000000,27700,21048.30
2,3,Campaign 3,2024-01-29 04:16:35.178,2024-02-19 04:16:35.178,Radio,Seniors,164528,2354,22242.000000,37043,31361.22
3,4,Campaign 4,2024-03-04 04:16:35.178,2024-03-21 04:16:35.178,Email,Young Adults,48765,2569,91.066667,11469,2732.00
4,5,Campaign 5,2023-11-08 04:16:35.178,2023-12-02 04:16:35.178,Search Engine,Families,356076,45973,1334.400000,35105,21016.80

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Campaign ID      50 non-null     int64
 1   Campaign Name    50 non-null     object
 2   Start Date       50 non-null     datetime64[ns]
 3   End Date         50 non-null     datetime64[ns]
 4   Channel          50 non-null     object
 5   Target Audience  50 non-null     object
 6   Impressions      50 non-null     int64
 7   Clicks           50 non-null     int64
 8   Bookings         50 non-null     float64
 9   Spend            50 non-null     int64
 10  Revenue          50 non-null     float64
dtypes: datetime64[ns](2), float64(2), int64(4), object(3)
memory usage: 4.4+ KB

In [10]:
df.isna().sum()

Campaign ID        0
Campaign Name      0
Start Date         0
End Date           0
Channel            0
Target Audience    0
Impressions        0
Clicks             0
Bookings           0
Spend              0
Revenue            0
dtype: int64

In [12]:
df['Channel'].value_counts()

Channel
Radio            11
Search Engine    10
Influencers       9
Billboards        6
Social Media      6
Email             4
TV                4
Name: count, dtype: int64

In [14]:
df['Target Audience'].value_counts()

Target Audience
Young Adults          15
Families              13
Seniors               12
Business Travelers    10
Name: count, dtype: int64

In [124]:
df['days'] =df['End Date'] - df['Start Date'] 
df.head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
0,1,Campaign 1,2024-02-02 04:16:35.177,2024-02-26 04:16:35.177,Radio,Seniors,24809,6540,2104.000000,18703,7048.40,24 days,-11654.60,0.376859
1,2,Campaign 2,2023-08-18 04:16:35.178,2023-09-03 04:16:35.178,Billboards,Seniors,193273,1154,11565.000000,27700,21048.30,16 days,-6651.70,0.759866
2,3,Campaign 3,2024-01-29 04:16:35.178,2024-02-19 04:16:35.178,Radio,Seniors,164528,2354,22242.000000,37043,31361.22,21 days,-5681.78,0.846617
3,4,Campaign 4,2024-03-04 04:16:35.178,2024-03-21 04:16:35.178,Email,Young Adults,48765,2569,91.066667,11469,2732.00,17 days,-8737.00,0.238207
4,5,Campaign 5,2023-11-08 04:16:35.178,2023-12-02 04:16:35.178,Search Engine,Families,356076,45973,1334.400000,35105,21016.80,24 days,-14088.20,0.598684

In [126]:
df['profit'] = df['Revenue'] - df['Spend']
df.head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
0,1,Campaign 1,2024-02-02 04:16:35.177,2024-02-26 04:16:35.177,Radio,Seniors,24809,6540,2104.000000,18703,7048.40,24 days,-11654.60,0.376859
1,2,Campaign 2,2023-08-18 04:16:35.178,2023-09-03 04:16:35.178,Billboards,Seniors,193273,1154,11565.000000,27700,21048.30,16 days,-6651.70,0.759866
2,3,Campaign 3,2024-01-29 04:16:35.178,2024-02-19 04:16:35.178,Radio,Seniors,164528,2354,22242.000000,37043,31361.22,21 days,-5681.78,0.846617
3,4,Campaign 4,2024-03-04 04:16:35.178,2024-03-21 04:16:35.178,Email,Young Adults,48765,2569,91.066667,11469,2732.00,17 days,-8737.00,0.238207
4,5,Campaign 5,2023-11-08 04:16:35.178,2023-12-02 04:16:35.178,Search Engine,Families,356076,45973,1334.400000,35105,21016.80,24 days,-14088.20,0.598684

In [20]:
df.groupby('Channel')['Bookings'].sum().round(1).nlargest(10)

Channel
Radio            89551.8
Billboards       53904.8
TV               35759.9
Influencers      35334.4
Search Engine    25466.1
Social Media     10611.1
Email             1484.4
Name: Bookings, dtype: float64

In [22]:
df.groupby('Channel')['Impressions'].sum().round(1).nlargest(10)

Channel
TV               2750198
Search Engine    2594228
Social Media     1478562
Radio            1324403
Influencers       917008
Billboards        797899
Email             134526
Name: Impressions, dtype: int64

In [24]:
df.groupby('Channel')['Clicks'].sum().round(1).nlargest(10)

Channel
Billboards       1152119
Search Engine     277851
Radio             252068
Influencers       160861
TV                151190
Social Media      129818
Email              11235
Name: Clicks, dtype: int64

In [128]:
df.head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
0,1,Campaign 1,2024-02-02 04:16:35.177,2024-02-26 04:16:35.177,Radio,Seniors,24809,6540,2104.000000,18703,7048.40,24 days,-11654.60,0.376859
1,2,Campaign 2,2023-08-18 04:16:35.178,2023-09-03 04:16:35.178,Billboards,Seniors,193273,1154,11565.000000,27700,21048.30,16 days,-6651.70,0.759866
2,3,Campaign 3,2024-01-29 04:16:35.178,2024-02-19 04:16:35.178,Radio,Seniors,164528,2354,22242.000000,37043,31361.22,21 days,-5681.78,0.846617
3,4,Campaign 4,2024-03-04 04:16:35.178,2024-03-21 04:16:35.178,Email,Young Adults,48765,2569,91.066667,11469,2732.00,17 days,-8737.00,0.238207
4,5,Campaign 5,2023-11-08 04:16:35.178,2023-12-02 04:16:35.178,Search Engine,Families,356076,45973,1334.400000,35105,21016.80,24 days,-14088.20,0.598684

# 1.	 Which company has the highest and lowest return?

In [130]:
df['revenue_per_spend'] = df['Revenue'] / df['Spend']
df.head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
0,1,Campaign 1,2024-02-02 04:16:35.177,2024-02-26 04:16:35.177,Radio,Seniors,24809,6540,2104.000000,18703,7048.40,24 days,-11654.60,0.376859
1,2,Campaign 2,2023-08-18 04:16:35.178,2023-09-03 04:16:35.178,Billboards,Seniors,193273,1154,11565.000000,27700,21048.30,16 days,-6651.70,0.759866
2,3,Campaign 3,2024-01-29 04:16:35.178,2024-02-19 04:16:35.178,Radio,Seniors,164528,2354,22242.000000,37043,31361.22,21 days,-5681.78,0.846617
3,4,Campaign 4,2024-03-04 04:16:35.178,2024-03-21 04:16:35.178,Email,Young Adults,48765,2569,91.066667,11469,2732.00,17 days,-8737.00,0.238207
4,5,Campaign 5,2023-11-08 04:16:35.178,2023-12-02 04:16:35.178,Search Engine,Families,356076,45973,1334.400000,35105,21016.80,24 days,-14088.20,0.598684

In [31]:
np.sort(df['revenue_per_spend'])

array([ 0.03956905,  0.09564684,  0.10186637,  0.17196337,  0.20187087,
        0.20290564,  0.22111123,  0.22585287,  0.23820734,  0.27607373,
        0.34747276,  0.37685933,  0.4070584 ,  0.41294315,  0.46093381,
        0.48877179,  0.54699102,  0.57113886,  0.57400029,  0.59868395,
        0.59971426,  0.60804751,  0.75986643,  0.76683777,  0.80920067,
        0.84055413,  0.84661663,  1.01154341,  1.10730664,  1.30792121,
        1.55230781,  1.8623871 ,  1.99207111,  2.02412966,  2.18995567,
        2.77107709,  2.93881177,  4.01200926,  4.0793165 ,  4.50171767,
        4.68903645,  4.95553391,  5.58537874,  6.13082143,  6.68638195,
        7.68146703,  8.67410494,  8.87005267,  9.77557704, 14.63653106])

In [136]:
df.sort_values(by='revenue_per_spend',ascending=False).head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
28,29,Campaign 29,2023-11-09 04:16:35.178,2023-12-01 04:16:35.178,Social Media,Families,233401,27448,4324.933333,6342,92824.88,22 days,86482.88,14.636531
13,14,Campaign 14,2024-01-05 04:16:35.178,2024-01-20 04:16:35.178,Influencers,Seniors,130765,31769,1334.866667,6828,66747.64,15 days,59919.64,9.775577
20,21,Campaign 21,2023-12-06 04:16:35.178,2023-12-19 04:16:35.178,Search Engine,Families,367359,8308,234.733333,21644,191983.42,13 days,170339.42,8.870053
22,23,Campaign 23,2024-04-23 04:16:35.178,2024-05-18 04:16:35.178,Search Engine,Business Travelers,278897,35192,757.133333,14865,128940.57,25 days,114075.57,8.674105
7,8,Campaign 8,2024-01-14 04:16:35.178,2024-02-09 04:16:35.178,TV,Families,994751,54630,759.533333,41976,322437.26,26 days,280461.26,7.681467

In [79]:
df[df['Campaign ID'] == 29]

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
28,29,Campaign 29,2023-11-09 04:16:35.178,2023-12-01 04:16:35.178,Social Media,Families,233401,27448,4324.933333,6342,92824.88,22 days,86482.88,14.636531

In [138]:
df[df['Channel']=='TV']

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
7,8,Campaign 8,2024-01-14 04:16:35.178,2024-02-09 04:16:35.178,TV,Families,994751,54630,759.533333,41976,322437.26,26 days,280461.26,7.681467
16,17,Campaign 17,2023-09-27 04:16:35.178,2023-09-27 04:16:35.178,TV,Families,381342,12541,476.133333,37254,167706.99,0 days,130452.99,4.501718
32,33,Campaign 33,2024-03-25 04:16:35.178,2024-04-12 04:16:35.178,TV,Seniors,988900,52774,594.200000,19231,90174.86,18 days,70943.86,4.689036
48,49,Campaign 49,2024-03-23 04:16:35.178,2024-04-06 04:16:35.178,TV,Young Adults,385205,31245,33930.000000,24019,147256.20,14 days,123237.20,6.130821

In [83]:
df['Start Date'].replace('2023-08-31 04:16:35.178','2023-09-27 04:16:35.178',inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_12300\2911406449.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Start Date'].replace('2023-08-31 04:16:35.178','2023-09-27 04:16:35.178',inplace=True)

In [85]:
df.to_excel('hotel.xlsx')

In [87]:
np.max(df['Start Date'])- np.min(df['Start Date'])

Timedelta('317 days 00:00:00')

# 2.	Which channel gets the most views, clicks and bookings?

In [140]:
df.sort_values(by='Impressions',ascending=False).head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
7,8,Campaign 8,2024-01-14 04:16:35.178,2024-02-09 04:16:35.178,TV,Families,994751,54630,759.533333,41976,322437.26,26 days,280461.26,7.681467
32,33,Campaign 33,2024-03-25 04:16:35.178,2024-04-12 04:16:35.178,TV,Seniors,988900,52774,594.200000,19231,90174.86,18 days,70943.86,4.689036
11,12,Campaign 12,2024-02-05 04:16:35.178,2024-02-18 04:16:35.178,Social Media,Business Travelers,486341,41253,1146.866667,17941,100207.28,13 days,82266.28,5.585379
25,26,Campaign 26,2024-03-27 04:16:35.178,2024-04-19 04:16:35.178,Search Engine,Young Adults,396600,44624,273.800000,10287,28506.07,23 days,18219.07,2.771077
48,49,Campaign 49,2024-03-23 04:16:35.178,2024-04-06 04:16:35.178,TV,Young Adults,385205,31245,33930.000000,24019,147256.20,14 days,123237.20,6.130821

In [142]:
df.sort_values(by='Bookings',ascending=False).round(0).head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
48,49,Campaign 49,2024-03-23 04:16:35.178,2024-04-06 04:16:35.178,TV,Young Adults,385205,31245,33930.0,24019,147256.0,14 days,123237.0,6.0
36,37,Campaign 37,2024-01-05 04:16:35.178,2024-01-21 04:16:35.178,Billboards,Young Adults,288090,987546,25627.0,33253,26908.0,16 days,-6345.0,1.0
2,3,Campaign 3,2024-01-29 04:16:35.178,2024-02-19 04:16:35.178,Radio,Seniors,164528,2354,22242.0,37043,31361.0,21 days,-5682.0,1.0
37,38,Campaign 38,2023-07-13 04:16:35.178,2023-07-31 04:16:35.178,Radio,Seniors,163087,5421,20826.0,47078,87677.0,18 days,40599.0,2.0
47,48,Campaign 48,2023-08-24 04:16:35.178,2023-09-03 04:16:35.178,Influencers,Families,126195,13436,14279.0,10256,41837.0,10 days,31581.0,4.0

In [144]:
df.sort_values(by='Clicks',ascending=False).head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
36,37,Campaign 37,2024-01-05 04:16:35.178,2024-01-21 04:16:35.178,Billboards,Young Adults,288090,987546,25627.000000,33253,26908.35,16 days,-6344.65,0.809201
34,35,Campaign 35,2023-09-14 04:16:35.178,2023-10-06 04:16:35.178,Billboards,Families,35569,78540,2262.000000,31614,5436.45,22 days,-26177.55,0.171963
33,34,Campaign 34,2024-03-21 04:16:35.178,2024-04-14 04:16:35.178,Radio,Families,93477,63210,951.933333,37293,7566.96,24 days,-29726.04,0.202906
27,28,Campaign 28,2023-11-27 04:16:35.178,2023-12-22 04:16:35.178,Radio,Families,90390,55741,1279.400000,13512,27350.04,25 days,13838.04,2.024130
21,22,Campaign 22,2023-07-06 04:16:35.178,2023-07-29 04:16:35.178,Billboards,Business Travelers,36949,55214,626.800000,27422,13403.10,23 days,-14018.90,0.488772

In [96]:
df[df['Channel']=="Billboards"]

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
1,2,Campaign 2,2023-08-18 04:16:35.178,2023-09-03 04:16:35.178,Billboards,Seniors,193273,1154,11565.0,27700,21048.30,16 days,-6651.70,0.759866
21,22,Campaign 22,2023-07-06 04:16:35.178,2023-07-29 04:16:35.178,Billboards,Business Travelers,36949,55214,626.8,27422,13403.10,23 days,-14018.90,0.488772
34,35,Campaign 35,2023-09-14 04:16:35.178,2023-10-06 04:16:35.178,Billboards,Families,35569,78540,2262.0,31614,5436.45,22 days,-26177.55,0.171963
36,37,Campaign 37,2024-01-05 04:16:35.178,2024-01-21 04:16:35.178,Billboards,Young Adults,288090,987546,25627.0,33253,26908.35,16 days,-6344.65,0.809201
40,41,Campaign 41,2023-06-21 04:16:35.178,2023-07-08 04:16:35.178,Billboards,Young Adults,185286,3215,7902.0,36037,8139.06,17 days,-27897.94,0.225853
44,45,Campaign 45,2023-07-04 04:16:35.178,2023-07-21 04:16:35.178,Billboards,Seniors,58732,26450,5922.0,6908,27714.96,17 days,20806.96,4.012009

In [98]:
df[df['Channel']=="Radio"]

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
0,1,Campaign 1,2024-02-02 04:16:35.177,2024-02-26 04:16:35.177,Radio,Seniors,24809,6540,2104.000000,18703,7048.40,24 days,-11654.60,0.376859
2,3,Campaign 3,2024-01-29 04:16:35.178,2024-02-19 04:16:35.178,Radio,Seniors,164528,2354,22242.000000,37043,31361.22,21 days,-5681.78,0.846617
6,7,Campaign 7,2024-02-02 04:16:35.178,2024-02-25 04:16:35.178,Radio,Families,196615,2541,5130.266667,31386,17167.86,23 days,-14218.14,0.546991
10,11,Campaign 11,2024-02-17 04:16:35.178,2024-03-05 04:16:35.178,Radio,Seniors,81877,25411,147.200000,44001,12147.52,17 days,-31853.48,0.276074
27,28,Campaign 28,2023-11-27 04:16:35.178,2023-12-22 04:16:35.178,Radio,Families,90390,55741,1279.400000,13512,27350.04,25 days,13838.04,2.024130
33,34,Campaign 34,2024-03-21 04:16:35.178,2024-04-14 04:16:35.178,Radio,Families,93477,63210,951.933333,37293,7566.96,24 days,-29726.04,0.202906
37,38,Campaign 38,2023-07-13 04:16:35.178,2023-07-31 04:16:35.178,Radio,Seniors,163087,5421,20826.000000,47078,87677.46,18 days,40599.46,1.862387
38,39,Campaign 39,2024-01-01 04:16:35.178,2024-01-11 04:16:35.178,Radio,Young Adults,65002,21346,1461.000000,45752,4660.59,10 days,-41091.41,0.101866
39,40,Campaign 40,2024-04-24 04:16:35.178,2024-05-15 04:16:35.178,Radio,Young Adults,157326,21346,13364.000000,22988,23253.36,21 days,265.36,1.011543
42,43,Campaign 43,2023-08-15 04:16:35.178,2023-09-12 04:16:35.178,Radio,Young Adults,145827,24513,11134.000000,5235,25942.22,28 days,20707.22,4.955534
45,46,Campaign 46,2024-05-01 04:16:35.178,2024-05-13 04:16:35.178,Radio,Business Travelers,141465,23645,10912.000000,13567,21060.16,12 days,7493.16,1.552308

In [100]:
df[df['Channel']=="Search Engine"]

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
4,5,Campaign 5,2023-11-08 04:16:35.178,2023-12-02 04:16:35.178,Search Engine,Families,356076,45973,1334.400000,35105,21016.80,24 days,-14088.20,0.598684
5,6,Campaign 6,2024-04-24 04:16:35.178,2024-05-06 04:16:35.178,Search Engine,Seniors,61949,11031,227.200000,47101,9508.32,12 days,-37592.68,0.201871
15,16,Campaign 16,2023-07-11 04:16:35.178,2023-07-24 04:16:35.178,Search Engine,Business Travelers,213880,26989,168.866667,25618,75286.48,13 days,49668.48,2.938812
20,21,Campaign 21,2023-12-06 04:16:35.178,2023-12-19 04:16:35.178,Search Engine,Families,367359,8308,234.733333,21644,191983.42,13 days,170339.42,8.870053
22,23,Campaign 23,2024-04-23 04:16:35.178,2024-05-18 04:16:35.178,Search Engine,Business Travelers,278897,35192,757.133333,14865,128940.57,25 days,114075.57,8.674105
25,26,Campaign 26,2024-03-27 04:16:35.178,2024-04-19 04:16:35.178,Search Engine,Young Adults,396600,44624,273.800000,10287,28506.07,23 days,18219.07,2.771077
29,30,Campaign 30,2023-08-18 04:16:35.178,2023-09-14 04:16:35.178,Search Engine,Young Adults,287940,47039,33.800000,48336,19960.02,27 days,-28375.98,0.412943
31,32,Campaign 32,2023-11-22 04:16:35.178,2023-12-14 04:16:35.178,Search Engine,Families,322107,10282,845.200000,32534,24948.30,22 days,-7585.70,0.766838
43,44,Campaign 44,2024-02-16 04:16:35.178,2024-03-13 04:16:35.178,Search Engine,Business Travelers,212312,38518,12678.000000,47929,27511.26,26 days,-20417.74,0.574000
46,47,Campaign 47,2023-09-16 04:16:35.178,2023-09-28 04:16:35.178,Search Engine,Young Adults,97108,9895,8913.000000,41298,14349.93,12 days,-26948.07,0.347473

In [102]:
df[df['Channel']=="Influencers"]

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
8,9,Campaign 9,2023-10-13 04:16:35.178,2023-10-26 04:16:35.178,Influencers,Business Travelers,107193,11662,758.866667,44051,37027.25,13 days,-7023.75,0.840554
9,10,Campaign 10,2023-06-19 04:16:35.178,2023-07-16 04:16:35.178,Influencers,Young Adults,139454,24787,2036.733333,7048,47125.62,27 days,40077.62,6.686382
13,14,Campaign 14,2024-01-05 04:16:35.178,2024-01-20 04:16:35.178,Influencers,Seniors,130765,31769,1334.866667,6828,66747.64,15 days,59919.64,9.775577
14,15,Campaign 15,2023-12-17 04:16:35.178,2024-01-05 04:16:35.178,Influencers,Families,140917,31405,3764.466667,6917,7659.24,19 days,742.24,1.107307
19,20,Campaign 20,2023-08-12 04:16:35.178,2023-08-31 04:16:35.178,Influencers,Young Adults,68682,15707,2061.400000,5009,3045.71,19 days,-1963.29,0.608048
30,31,Campaign 31,2023-11-07 04:16:35.178,2023-12-01 04:16:35.178,Influencers,Business Travelers,70479,15171,151.066667,24216,31672.62,24 days,7456.62,1.307921
41,42,Campaign 42,2023-11-30 04:16:35.178,2023-12-20 04:16:35.178,Influencers,Seniors,39071,2719,2266.000000,17219,9834.44,20 days,-7384.56,0.571139
47,48,Campaign 48,2023-08-24 04:16:35.178,2023-09-03 04:16:35.178,Influencers,Families,126195,13436,14279.000000,10256,41837.47,10 days,31581.47,4.079316
49,50,Campaign 50,2024-02-13 04:16:35.178,2024-03-03 04:16:35.178,Influencers,Business Travelers,94252,14205,8682.000000,13162,26219.64,19 days,13057.64,1.992071

In [104]:
df[df['Channel']=="Social Media"]

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
11,12,Campaign 12,2024-02-05 04:16:35.178,2024-02-18 04:16:35.178,Social Media,Business Travelers,486341,41253,1146.866667,17941,100207.28,13 days,82266.28,5.585379
12,13,Campaign 13,2023-12-15 04:16:35.178,2023-12-26 04:16:35.178,Social Media,Business Travelers,213121,18476,205.066667,47533,10510.08,11 days,-37022.92,0.221111
18,19,Campaign 19,2023-11-05 04:16:35.178,2023-11-16 04:16:35.178,Social Media,Families,51252,3373,2850.533333,25128,15069.62,11 days,-10058.38,0.599714
23,24,Campaign 24,2023-09-05 04:16:35.178,2023-09-29 04:16:35.178,Social Media,Young Adults,188013,11268,295.200000,7219,15809.29,24 days,8590.29,2.189956
24,25,Campaign 25,2023-09-22 04:16:35.178,2023-10-09 04:16:35.178,Social Media,Seniors,306434,28000,1788.533333,44809,18239.88,17 days,-26569.12,0.407058
28,29,Campaign 29,2023-11-09 04:16:35.178,2023-12-01 04:16:35.178,Social Media,Families,233401,27448,4324.933333,6342,92824.88,22 days,86482.88,14.636531

In [106]:
df[df['Channel']=="Email"]

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
3,4,Campaign 4,2024-03-04 04:16:35.178,2024-03-21 04:16:35.178,Email,Young Adults,48765,2569,91.066667,11469,2732.00,17 days,-8737.00,0.238207
17,18,Campaign 18,2023-07-26 04:16:35.178,2023-08-16 04:16:35.178,Email,Young Adults,29758,2222,197.133333,44756,4280.77,21 days,-40475.23,0.095647
26,27,Campaign 27,2024-03-17 04:16:35.178,2024-04-03 04:16:35.178,Email,Young Adults,41703,5770,617.400000,39387,18154.80,17 days,-21232.20,0.460934
35,36,Campaign 36,2023-06-30 04:16:35.178,2023-07-10 04:16:35.178,Email,Seniors,14300,674,578.800000,41258,1632.54,10 days,-39625.46,0.039569

In [108]:
df.groupby('Channel')['profit'].sum().nlargest(10)

Channel
TV               605095.31
Search Engine    217294.17
Influencers      136463.63
Social Media     103689.03
Radio            -51322.21
Billboards       -60283.78
Email           -110069.89
Name: profit, dtype: float64

# 3.	What is the highest return category?

In [111]:
df.groupby('Target Audience')['profit'].sum().nlargest(10)

Target Audience
Families              612044.29
Business Travelers    195534.44
Seniors                25256.54
Young Adults            8030.99
Name: profit, dtype: float64

# 4.	Which company provided the lowest return and highest cost?

In [114]:
df.groupby('Channel')['profit'].sum().nsmallest(10)

Channel
Email           -110069.89
Billboards       -60283.78
Radio            -51322.21
Social Media     103689.03
Influencers      136463.63
Search Engine    217294.17
TV               605095.31
Name: profit, dtype: float64

In [148]:
df.sort_values(by='Spend',ascending=False).head(10)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
29,30,Campaign 30,2023-08-18 04:16:35.178,2023-09-14 04:16:35.178,Search Engine,Young Adults,287940,47039,33.800000,48336,19960.02,27 days,-28375.98,0.412943
43,44,Campaign 44,2024-02-16 04:16:35.178,2024-03-13 04:16:35.178,Search Engine,Business Travelers,212312,38518,12678.000000,47929,27511.26,26 days,-20417.74,0.574000
12,13,Campaign 13,2023-12-15 04:16:35.178,2023-12-26 04:16:35.178,Social Media,Business Travelers,213121,18476,205.066667,47533,10510.08,11 days,-37022.92,0.221111
5,6,Campaign 6,2024-04-24 04:16:35.178,2024-05-06 04:16:35.178,Search Engine,Seniors,61949,11031,227.200000,47101,9508.32,12 days,-37592.68,0.201871
37,38,Campaign 38,2023-07-13 04:16:35.178,2023-07-31 04:16:35.178,Radio,Seniors,163087,5421,20826.000000,47078,87677.46,18 days,40599.46,1.862387
38,39,Campaign 39,2024-01-01 04:16:35.178,2024-01-11 04:16:35.178,Radio,Young Adults,65002,21346,1461.000000,45752,4660.59,10 days,-41091.41,0.101866
24,25,Campaign 25,2023-09-22 04:16:35.178,2023-10-09 04:16:35.178,Social Media,Seniors,306434,28000,1788.533333,44809,18239.88,17 days,-26569.12,0.407058
17,18,Campaign 18,2023-07-26 04:16:35.178,2023-08-16 04:16:35.178,Email,Young Adults,29758,2222,197.133333,44756,4280.77,21 days,-40475.23,0.095647
8,9,Campaign 9,2023-10-13 04:16:35.178,2023-10-26 04:16:35.178,Influencers,Business Travelers,107193,11662,758.866667,44051,37027.25,13 days,-7023.75,0.840554
10,11,Campaign 11,2024-02-17 04:16:35.178,2024-03-05 04:16:35.178,Radio,Seniors,81877,25411,147.200000,44001,12147.52,17 days,-31853.48,0.276074

In [150]:
df.sort_values(by='profit',ascending=True).head(5)

,Campaign ID,Campaign Name,Start Date,End Date,Channel,Target Audience,Impressions,Clicks,Bookings,Spend,Revenue,days,profit,revenue_per_spend
38,39,Campaign 39,2024-01-01 04:16:35.178,2024-01-11 04:16:35.178,Radio,Young Adults,65002,21346,1461.000000,45752,4660.59,10 days,-41091.41,0.101866
17,18,Campaign 18,2023-07-26 04:16:35.178,2023-08-16 04:16:35.178,Email,Young Adults,29758,2222,197.133333,44756,4280.77,21 days,-40475.23,0.095647
35,36,Campaign 36,2023-06-30 04:16:35.178,2023-07-10 04:16:35.178,Email,Seniors,14300,674,578.800000,41258,1632.54,10 days,-39625.46,0.039569
5,6,Campaign 6,2024-04-24 04:16:35.178,2024-05-06 04:16:35.178,Search Engine,Seniors,61949,11031,227.200000,47101,9508.32,12 days,-37592.68,0.201871
12,13,Campaign 13,2023-12-15 04:16:35.178,2023-12-26 04:16:35.178,Social Media,Business Travelers,213121,18476,205.066667,47533,10510.08,11 days,-37022.92,0.221111

In [120]:
df[df['Start Date']=='2023-07-13']

Empty DataFrame
Columns: [Campaign ID, Campaign Name, Start Date, End Date, Channel, Target Audience, Impressions, Clicks, Bookings, Spend, Revenue, days, profit, revenue_per_spend]
Index: []

# 5.	What was the period with the highest booking rate?

### January

# 6.	What is the best marketing channel?

### It is through television, as it offers the highest return and the highest number of reservations.